### ISSUE TITLE
SQLite Database of known Bots

### ISSUE THREAD

**Issue by ghost** [therealnagia/twitchbanfromlist#5]
I have a large list of known lurkerbots
[GoogleDrive](https://drive.google.com/file/d/1gREDoSGTYtQaLzgrinaweTblyGsJvgch/view)

i did an pullrequest in golang
adding this database to autoban is easy in Go
also you can track already banned accounts
so future ban process doesnt need to go trough the complete list

**Comment by therealnagia** [comment]
Thank you for the resources but I've decided we will use personally vetted bot lists. It may not be comprehensive or as effective, but that's what options are for (as the script can be run with any list) 😄
