### ISSUE TITLE
how do i delete it?

### ISSUE THREAD

**Issue by summerreigns** [therealnagia/twitchbanfromlist#7]
hi i ran it and it worked perfectly but now i wanna get rid of the keybind command, so how do i do that?

**Comment by therealnagia** [comment]
Hi there, I'm glad it worked for you! Once the program completes, it exits
and returns your normal key bindings.

If you re-open it you should see a green H icon in your system tray.

Simply hit Esc key anytime to close the program! (It will disappear from
your system tray) Let me know if that works for you.

**Comment by summerreigns** [comment]
i actually found out how to do it by closing it through Task Manager! but thank you so much for this. <3!!

**Comment by therealnagia** [comment]
Sounds good! I'm glad you figured out something! You're very much welcome :)
